### ISSUE TITLE
Non apply numeric standard transform 

### ISSUE THREAD

**Issue by ThanhHung2112** [Automunge/AutoMunge#1615] opened 2024-03-26 03:55 UTC
Any changes that could allow us to apply transformations solely to categorical data while preserving the original format of numeric data upon inputting the data source?

**Comment by gatorwatt** [comment] 2024-12-30 17:05
This is a question about how to navigate API, not a bug, so am closing this ticket.

**Closed as completed** 2024-12-30 17:06 UTC
